name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2

      - name: Install dependencies
        run: go get -d -v

      - name: Run unit tests
        run: go test --cover -coverprofile="coverage.out" ./... 
        
      - name: Upload coverage report
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
